### ISSUE TITLE
content align

### ISSUE THREAD

**Issue by jijip41** [fac22/Sunny_North_London_Agency#4]
Hi Saira
I've just found that all content are aligned left. Would prefer to centre them, what do you think? If you don't mind, I can fix it let me know:)

**Comment by sb5346** [comment]
Hello Ji, just to confirm you would prefer the content block centre-aligned, not the text? As I understand, left-aligned text is easier to read.
I can add more padding or change the width and see how it looks. I have not otherwise set any alignment in what I have called maincontainer and sectioncontainer or footer. So it is not specifically left-aligned.
It was because I just kept a simple responsive layout and only used flex-display with one column. It seems it automatically starts at the left.
I have tested on my Chrome browser only so far, but when you publish and make the publicly accessible domain name, I can test on my phone browser too.
Also, can you confirm you do not want any more columns? I prefer the simple flex, single column of content. But let me know what you think.

**Comment by jijip41** [comment]
Hi Saira 
I mean the containers on the page should sit in the centre of the page. At the moment, the block that contains the text is sitting to the left of the page. You're right that the text should be aligned left, but the container (main element) should be in the centre of the page.

**Comment by sb5346** [comment]
Hello Ji, I updated the css. the content blocks are off from the left.
The images I added don't seem to be working at the moment though you should be able to see the content alignment.

**Comment by jijip41** [comment]
Hi Saira. changed img to font awesome code. I think it looks good on my side. I created pull request so check it then merge it please.
